### ISSUE TITLE
Add example file for the rules that can be used

### ISSUE THREAD

**Issue by rajbos** [bp4151/cvss-rescore#6]
I was lookin for how I can use this with rules and looked for examples. Eventually I found the rules.rst but that did not really clarify things. Additionally this should be up front in the README I’d say.

**Comment by bp4151** [comment]
> I was lookin for how I can use this with rules and looked for examples. Eventually I found the rules.rst but that did not really clarify things. Additionally this should be up front in the README I’d say. 

Thank you for your submission!
- I am working on a full script example that users can run locally. It's code complete but I'm waiting for maintainers to test it prior to release.
- To better understand rule grammar, you can visit the rule-engine package documentation at https://zerosteiner.github.io/rule-engine/    You will also need an understanding of cvss scoring which is available at
https://www.first.org/cvss/calculator/3.1   
https://www.first.org/cvss/specification-document   
https://www.first.org/cvss/user-guide   
https://www.first.org/cvss/examples  
- We are separating the rule information to a separate file as the various files also drive the documentation at readthedocs.io

Beyond that, it's really up to user imagination and an understanding of how their environment impacts their use of packages.
